import type { Container, Item } from './model';
export const demoBag: Container = {
  name: 'Weekend carry',
  dims: [32, 48, 20],
  opening: [31, 19],
  maxMass: 7,
  expansion: 0.2,
};
const base = {
  rigidity: 'rigid',
  minRatio: 1,
  fragile: false,
  orientation: 'any',
  access: 'normal',
  required: true,
  maxTopLoad: 4,
  source: 'sample',
  confidence: 1,
  notes: 'Sample measurements. Check your own item before packing.',
} as const;
export const demoItems: Item[] = [
  {
    ...base,
    id: 'headphones',
    name: 'Headphones',
    dims: [19, 8, 17],
    mass: 0.28,
    color: '#b391ea',
    maxTopLoad: 0.7,
  },
  {
    ...base,
    id: 'laptop',
    name: 'Laptop',
    dims: [30, 36, 2],
    mass: 1.4,
    color: '#678baa',
    orientation: 'upright',
    maxTopLoad: 0,
  },
  {
    ...base,
    id: 'shoes',
    name: 'Shoes',
    dims: [28, 10, 17],
    mass: 0.72,
    color: '#d9a25c',
    maxTopLoad: 5,
  },
  {
    ...base,
    id: 'camera',
    name: 'Camera',
    dims: [14, 10, 10],
    mass: 0.65,
    color: '#52b9a3',
    fragile: true,
    maxTopLoad: 0,
  },
  {
    ...base,
    id: 'bottle',
    name: 'Water bottle',
    dims: [8, 25, 8],
    mass: 0.8,
    color: '#70aadb',
    orientation: 'upright',
    maxTopLoad: 0,
  },
  {
    ...base,
    id: 'hoodie',
    name: 'Hoodie',
    dims: [28, 10, 17],
    mass: 0.48,
    color: '#e78d84',
    rigidity: 'soft',
    minRatio: 0.6,
    maxTopLoad: 2,
  },
  {
    ...base,
    id: 'powerbank',
    name: 'Power bank',
    dims: [8, 3, 14],
    mass: 0.32,
    color: '#d6bd65',
    maxTopLoad: 4,
  },
  {
    ...base,
    id: 'shirts',
    name: 'Two folded T-shirts',
    dims: [18, 6, 16],
    mass: 0.3,
    color: '#90ae93',
    rigidity: 'soft',
    minRatio: 0.7,
    maxTopLoad: 2,
  },
];
export const freshDemo = () => ({
  items: structuredClone(demoItems),
  bag: structuredClone(demoBag),
});
